#!/bin/sh
echo "Enter query"
query=$(read query ; echo $query | tr ' ' '+')
echo "https://1337xxx.to/search/$query/1/"
movie=$(curl https://1337xxx.to/search/$query/1/ | grep -Eo "torrent\/[0-9]{7}\/[a-zA-Z0-9?%-]*/" | head -n 1)
echo $movie
magnet=$(curl https://1337xxx.to/$movie | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
echo $magnet
peerflix -k $magnet
